[contextpilot]
source = "github"
github = "krshrimali/context-pilot-rs"

[contextpilot-git]
source = "git"
git = "https://github.com/krshrimali/context-pilot-rs.git"
use_commit = true
branch = "main"

[terminal-rain-lightning]
source = "github"
github = "rmaake1/terminal-rain-lightning"
pypi = "terminal-rain-lightning"

[twmd-bin]
source = "github"
github = "mmpx12/twitter-media-downloader"

[twitter-media-downloader-git]
source = "github"
github = "mmpx12/twitter-media-downloader"

[smithery-cli]
source = "github"
github = "smithery-ai/cli"

[relax-player]
source = "github"
github = "ebithril/relax-player"

[onionmine-git]
source = "gitlab"
gitlab = "tpo/onion-services/onionmine"
use_commit = true
branch = "main"

[onionspray]
source = "gitlab"
gitlab = "tpo/onion-services/onionspray"
